### ISSUE TITLE
Upstream trace pretty-printer from Foundry

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/revm-inspectors#14]
The main code lives here: https://github.com/foundry-rs/foundry/blob/4c73702d605287c39cb73a6d9a6879c5c3ead0dc/crates/evm/traces/src/lib.rs#L70

This should be refactored into a pretty-printer struct generic over a `Write` writer ~~and an optional `TraceDecoder` trait used to decode the traces before printing them~~.

Trace decoding should be kept outside of this crate by adding optional "decoded" fields for call data and return data.

**Comment by klkvr** [comment]
@DaniPopes why it was chosen to keep decoding logic in foundry?

the idea is to add additional `decoded_call`, `decoded_return`, etc to CallTrace right?

**Comment by DaniPopes** [comment]
It's not strictly necessary to be upstreamed and the current implementation is very foundry specific

**Comment by zerosnacks** [comment]
.
