### ISSUE TITLE
Memory recording improvements

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/revm-inspectors#64]
Currently, if 

https://github.com/paradigmxyz/evm-inspectors/blob/846dec1db14ac42067e7a4bb6a973091cd7eb808/src/tracing/config.rs#L15-L16

is enabled memory, memory is cloned on each step:

https://github.com/paradigmxyz/evm-inspectors/blob/846dec1db14ac42067e7a4bb6a973091cd7eb808/src/tracing/mod.rs#L306-L310

there are only a few opcodes that modify memory, so we can optimize this and only record memory when necessary.
This is also only relevant for the parity vmtrace setting:

https://github.com/paradigmxyz/evm-inspectors/blob/846dec1db14ac42067e7a4bb6a973091cd7eb808/src/tracing/builder/parity.rs#L383-L390

**Comment by h3lio5** [comment]
> there are only a few opcodes that modify memory, so we can optimize this and only record memory when necessary.   

A naive approach that comes to mind is to have a HashMap (OpCode => bool) that contains info if an OpCode modifies memory, record memory only if the hashmap entry is true. Can you please suggest a good way to do it?

**Comment by mattsse** [comment]
yep, great idea!

we've since added something similar to foundry:

https://github.com/foundry-rs/foundry/blob/1281421e04144a8de0341f9cad9b623a012a74bf/crates/evm/core/src/opcodes.rs#L5-L25

which we use for efficient memory recording as well:

https://github.com/foundry-rs/foundry/blob/1281421e04144a8de0341f9cad9b623a012a74bf/crates/evm/evm/src/inspectors/debugger.rs#L75-L81

so we can move this function in here and do the same trick

**Comment by h3lio5** [comment]
@mattsse yes, please assign me!

**Comment by rakita** [comment]
Oh, it would be good to move `modifies_memory` to revm, so it is easy to reuse.

**Comment by mattsse** [comment]
great!

@h3lio5 do you want to take care of that as well?

**Comment by h3lio5** [comment]
@mattsse sure, I'll port it over to revm also.
