### ISSUE TITLE
Use borrowed Arena in GethTraceBuilder 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/revm-inspectors#65]
This should be a cow instead:

https://github.com/paradigmxyz/evm-inspectors/blob/846dec1db14ac42067e7a4bb6a973091cd7eb808/src/tracing/builder/geth.rs#L18-L20

together with:

https://github.com/paradigmxyz/evm-inspectors/pull/63

this would allows us to use an inspector across multiple transact calls, reusing allocated memory

**Comment by nkysg** [comment]
Let me try it.

**Comment by DaniPopes** [comment]
I believe this also applies to the other builders? @mattsse
